HelpDeskTicket/Components/NavBarViewComponent.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;



namespace HelpDeskTicket.Views.Shared.Components
{
    public class NavBarViewComponent : ViewComponent
    {
        public async Task <IViewComponentResult> InvokeAsync ()
        {
            return View();
        }
    }
}

HelpDeskTicket/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using HelpDeskTicket.Models;
using Microsoft.AspNetCore.Authorization;

namespace HelpDeskTicket.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        //ctor, brings in iLogger of type HomeController
        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        [Authorize]
        public IActionResult Index()
        {           
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }

       

    }
}

HelpDeskTicket/Controllers/TicketsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using HelpDeskTicket.Data;
using HelpDeskTicket.Models;
using Microsoft.AspNetCore.Http;
using System.IO;
using Microsoft.AspNetCore.Identity;
using PagedList;


namespace HelpDeskTicket.Controllers
{
    public class TicketsController : Controller
    {
        private readonly ApplicationDbContext _context;
        private readonly UserManager<Employee> _userManager;

        public TicketsController(ApplicationDbContext context, UserManager<Employee> userManager)
        {
            _context = context;
            _userManager = userManager;
        }

        // GET: Tickets
        //[Microsoft.AspNetCore.Authorization.Authorize]
        public async Task<IActionResult> Index(string sortOrder, string currentFilter, string searchString, int? pageNumber)
        {
            if (searchString != null)
            {
                pageNumber = 1;
            }
            else
            {
                searchString = currentFilter;
            }

            var tickets =  _context.Tickets;
            var ticketModels = tickets.Select(ticket => new TicketModel
            {
                Department = ticket.Department,
                Title = ticket.Title,
                TicketDescription = ticket.TicketDescription,
                Id = ticket.Id
            });

             int pageSize = 3;
           
                return View(await PaginatedList<Ticket>.CreateAsync(tickets.AsNoTracking(), pageNumber ?? 1, pageSize));
                //return View(ticketModels);
        }

        // GET: Tickets/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var ticket = await _context.Tickets
                .FirstOrDefaultAsync(m => m.Id == id);
            if (ticket == null)
            {
                return NotFound();
            }

            return View(ticket);
        }

        // GET: Tickets/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Tickets/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(TicketModel ticketModel)
        {
            //if TicketModel is valid, take all data from the ticektModel and 
            //store it into the DB.
            if (ModelState.IsValid)
            {
                var email = HttpContext.User.Identity.Name;
                var employee = await _userManager.FindByNameAsync(email);

                var ticket = new Ticket
                {
                    Department = ticketModel.Department,
                    Title = ticketModel.Title,
                    TicketDescription = ticketModel.TicketDescription,
                    CreatedDate = DateTime.Now,
                    Status = TicketStatus.Unresolved,
                    EmployeeId = employee.Id,
                    EmployeeName = employee.Name
                }; 
                            
                if (ticketModel.Attachment != null)
                {
                    var attachment = ticketModel.Attachment;
                    using(var ms = new MemoryStream())
                    {
                        attachment.CopyTo(ms);
                        ticket.Attachment = ms.ToArray();
                        ticket.AttachmentName = Path.GetFileNameWithoutExtension(attachment.FileName);
                        ticket.AttachmentExtension = Path.GetExtension(attachment.FileName);
                    }
                }

                _context.Add(ticket);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(ticketModel);
        }

        // GET: Tickets/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var ticket = await _context.Tickets.FindAsync(id);
            if (ticket == null)
            {
                return NotFound();
            }
            return View(ticket);
        }

        // POST: Tickets/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, TicketModel ticketModel)
        {
            if (id != ticketModel.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                //try
                //{
                //    _context.Update(ticket);
                //    await _context.SaveChangesAsync();
                //}
                //catch (DbUpdateConcurrencyException)
                //{
                //    if (!TicketExists(ticket.Id))
                //    {
                //        return NotFound();
                //    }
                //    else
                //    {
                //        throw;
                //    }
                //}
                //return RedirectToAction(nameof(Index));
            }
            return View(ticketModel);
        }

        // GET: Tickets/Delete/5
        
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var ticket = await _context.Tickets
                .FirstOrDefaultAsync(m => m.Id == id);
            if (ticket == null)
            {
                return NotFound();
            }

            return View(ticket);
        }

        // POST: Tickets/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var ticket = await _context.Tickets.FindAsync(id);
            _context.Tickets.Remove(ticket);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool TicketExists(int id)
        {
            return _context.Tickets.Any(e => e.Id == id);
        }

        public IActionResult MyTickets(Employee employee) => View();
    }
}

HelpDeskTicket/Views/Home/Index.cshtml
@model HelpDeskTicket.Models.TicketModel

@{
    ViewData["Title"] = "Index";
}
@addTagHelper *, Microsoft.AspNetCore.Mvc.TagHelpers

<head>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
</head>

<style>
    .text-center{
        margin-bottom:50px;
    }
</style>

<div class="container">
    @await Component.InvokeAsync("NavBar")  

    <div class="text-center">
        <h1 class="display-4">Welcome John</h1>
    </div>

    <div class="container" id="dashboard">


        <!--BEGINNING FOUR CARDS CONTAINER-->
        <div class="row mx-0" id="four-cards-container">
            <div class="col-md-3 col-12">
                <div class="card ticket-item-box" id="submit-tickets">
                    <div class="card-header">
                        <strong>Submit</strong> Tickets
                    </div>

                    <div class="container">
                        <div class="row justify-content-center my-4">
                            <a asp-controller="Tickets" asp-action="Create" class="btn btn-primary">Submit</a>
                        </div>
                    </div>
                </div>
            </div>

            <div class="col-md-3 col-12">
                <div class="card ticket-item-box" id="unresolved-tickets">
                    <div class="card-header">
                        <strong>Unresolved</strong> Tickets
                    </div>
                    <div class="container" id="index-page-unresolved-tickets">
                        <div class="row justify-content-center my-4">
                            <div class="stat-digit">
                                <i class="fa fa-ticket" aria-hidden="true"></i>
                                0
                            </div>
                        </div>
                    </div>
                </div>
            </div>

            <div class="col-md-3 col-12">
                <div class="card ticket-item-box" id="tickets-in-progress">
                    <div class="card-header">
                        <strong>Tickets</strong> in progress
                    </div>
                    <div class="container">
                        <div class="row justify-content-center my-4">
                            <div class="stat-digit">
                                <i class="fa fa-ticket" aria-hidden="true"></i>
                                0
                            </div>
                        </div>
                    </div>
                </div>
            </div>

            <div class="col-md-3 col-12">
                <div class="card ticket-item-box" id="my-tickets">
                    <div class="card-header">
                        <strong>My</strong> Tickets
                    </div>
                    <div class="container">
                        <div class="row justify-content-center my-4">
                            <a asp-controller="Tickets" asp-action="MyTickets" class="btn btn-primary">View</a>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <!--ENDING FOUR CARDS CONTAINER-->



    </div>
</div>

HelpDeskTicket/Views/Home/SubmitTicket.cshtml
@{
    ViewData["Title"] = "SubmitTicket";
}

    <div class="card">
        <div class="submit-form">
            <div class="card-header">
                <strong>Submit</strong> Ticket
            </div>

            <form action="">

                <!--name-->
                <div class="row form-group">
                    <div class="col col-md-3">
                        <label for="submit-name-input" class=" form-control-label">Your Name</label>
                    </div>
                    <div class="col-12 col-md-9">
                        <input type="password" id="name-input" name="name-input" placeholder="Name" class="form-control">
                        <small class="help-block form-text">Please enter your name</small>
                    </div>
                </div>

                <!--title-->
                <div class="row form-group">
                    <div class="col col-md-3">
                        <label for="submit-title-input" class=" form-control-label">Title</label>
                    </div>
                    <div class="col-12 col-md-9">
                        <input type="title" id="title-input" name="title-input" placeholder="Title" class="form-control">
                        <small class="help-block form-text">Please give this ticket a title</small>
                    </div>
                </div>

                <!--ticket info-->
                <div class="row form-group">
                    <div class="col col-md-3">
                        <label for="ticket-content-input" class=" form-control-label">Content</label>
                    </div>
                    <div class="col-12 col-md-9">
                        <grammarly-extension style="position: absolute; top: 0px; left: 0px; pointer-events: none;" class="_1KJtL"></grammarly-extension>
                        <textarea name="submit-content-input" id="submit-content-input" rows="9" placeholder="Please describe your issue" class="form-control" spellcheck="false"></textarea>
                    </div>
                </div>

                <div class="col col-sm-5">
                    <label for="chooseFile">Attachment:</label>
                    <input accept="image/*" type="File" /><br>
                </div>

                <div class="card-footer">
                    <button type="submit" class="btn btn-primary btn-sm">
                        <i class="fa fa-dot-circle-o"></i> Submit
                    </button>
                    <button type="reset" class="btn btn-danger btn-sm">
                        <i class="fa fa-ban"></i> Reset
                    </button>
                </div>
            </form>
        </div>
    </div>